### PR TITLE
Removes sections and paragraphs on functional naming

### PR DESCRIPTION
**Pull request by florian-stefan**
This PR removes the sections on functional naming and updates the paragraphs that reference those sections.

### CODE REVIEW

**Comment by gilbertotcc** [comment]
@soblom IMHO If our approach is to fork the guidelines we might accept holes in the numbering.

There are two useful scripts to: [check for ids conflicts](https://github.com/infinitecsolutions/restful-api-guidelines/blob/master/check_rule_ids.sh) and to [get the next rule id](https://github.com/infinitecsolutions/restful-api-guidelines/blob/master/new_rule_id.sh).

**Comment by soblom** [comment]
@gilbertotcc That works for me.

I guess we need to add a note somewhere (maybe just in the `README`) to explain what is up with the "weird" numbers. Regarding new IDs we are always at risk of conflicting with new Zalando IDs, if we use the same logic as in that script 😃 

But I don't want to hijack this PR with such a general discussion. Let's figure it out as  we go.

**Comment by gilbertotcc** [comment]
@soblom To avoid conflicts we can also use custom numbering (e.g. `infinitecX`) for our rules and create similar scripts to get the next id and check for conflicts. But I agree with you that this can be done in another pull request.

**Comment by apankowski** [comment]
@soblom @gilbertotcc I was about to propose what Gilberto said - unless you think it's completely stupid, I'd leave the Zalando numbering intact and allow for gaps in numeration (because we've deleted something). I'd use our own, parallel numeration like `IS001` or `X001` (because X doesn't look like any digit) for our own guidelines.

**Pull request merged**
